webpackJsonp([11],{

/***/ "../../../../../src/$$_gendir/app/blog/doctors/doctors.module.ngfactory.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/@angular/core.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_blog_doctors_doctors_module__ = __webpack_require__("../../../../../src/app/blog/doctors/doctors.module.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__doctors_component_ngfactory__ = __webpack_require__("../../../../../src/$$_gendir/app/blog/doctors/doctors.component.ngfactory.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_common__ = __webpack_require__("../../../common/@angular/common.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__angular_router__ = __webpack_require__("../../../router/@angular/router.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__app_blog_doctors_doctors_component__ = __webpack_require__("../../../../../src/app/blog/doctors/doctors.component.ts");
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "DoctorsModuleNgFactory", function() { return DoctorsModuleNgFactory; });
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */






var DoctorsModuleNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵcmf"](__WEBPACK_IMPORTED_MODULE_1__app_blog_doctors_doctors_module__["a" /* DoctorsModule */], [], function (_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmod"]([__WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_0__angular_core__["ComponentFactoryResolver"], __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵCodegenComponentFactoryResolver"], [[8, [__WEBPACK_IMPORTED_MODULE_2__doctors_component_ngfactory__["a" /* DoctorsComponentNgFactory */]]], [3, __WEBPACK_IMPORTED_MODULE_0__angular_core__["ComponentFactoryResolver"]], __WEBPACK_IMPORTED_MODULE_0__angular_core__["NgModuleRef"]]),
        __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](4608, __WEBPACK_IMPORTED_MODULE_3__angular_common__["NgLocalization"], __WEBPACK_IMPORTED_MODULE_3__angular_common__["NgLocaleLocalization"], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["LOCALE_ID"]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_3__angular_common__["CommonModule"], __WEBPACK_IMPORTED_MODULE_3__angular_common__["CommonModule"], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_4__angular_router__["x" /* RouterModule */], __WEBPACK_IMPORTED_MODULE_4__angular_router__["x" /* RouterModule */], [[2, __WEBPACK_IMPORTED_MODULE_4__angular_router__["k" /* ɵa */]], [2, __WEBPACK_IMPORTED_MODULE_4__angular_router__["d" /* Router */]]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_1__app_blog_doctors_doctors_module__["a" /* DoctorsModule */], __WEBPACK_IMPORTED_MODULE_1__app_blog_doctors_doctors_module__["a" /* DoctorsModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](1024, __WEBPACK_IMPORTED_MODULE_4__angular_router__["t" /* ROUTES */], function () {
            return [[{ path: '', component: __WEBPACK_IMPORTED_MODULE_5__app_blog_doctors_doctors_component__["a" /* DoctorsComponent */], children: [] }]];
        }, [])]);
});
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ3JlYXQtc3Rhci9naXQvZGVudGNhd2ViL2Zyb250ZW5kL3NyYy9hcHAvYmxvZy9kb2N0b3JzL2RvY3RvcnMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZ3JlYXQtc3Rhci9naXQvZGVudGNhd2ViL2Zyb250ZW5kL3NyYy9hcHAvYmxvZy9kb2N0b3JzL2RvY3RvcnMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
//# sourceMappingURL=doctors.module.ngfactory.js.map

/***/ })

});
//# sourceMappingURL=11.chunk.js.map