webpackJsonp(["blog.module"],{

/***/ "../../../../../src/$$_gendir/app/blog/blog.module.ngfactory.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "BlogModuleNgFactory", function() { return BlogModuleNgFactory; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/@angular/core.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__app_blog_blog_module__ = __webpack_require__("../../../../../src/app/blog/blog.module.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common__ = __webpack_require__("../../../common/@angular/common.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_router__ = __webpack_require__("../../../router/@angular/router.es5.js");
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */




var BlogModuleNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵcmf"](__WEBPACK_IMPORTED_MODULE_1__app_blog_blog_module__["a" /* BlogModule */], [], function (_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmod"]([__WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_0__angular_core__["ComponentFactoryResolver"], __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵCodegenComponentFactoryResolver"], [[8, []], [3, __WEBPACK_IMPORTED_MODULE_0__angular_core__["ComponentFactoryResolver"]], __WEBPACK_IMPORTED_MODULE_0__angular_core__["NgModuleRef"]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](4608, __WEBPACK_IMPORTED_MODULE_2__angular_common__["NgLocalization"], __WEBPACK_IMPORTED_MODULE_2__angular_common__["NgLocaleLocalization"], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["LOCALE_ID"]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_2__angular_common__["CommonModule"], __WEBPACK_IMPORTED_MODULE_2__angular_common__["CommonModule"], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_3__angular_router__["p" /* RouterModule */], __WEBPACK_IMPORTED_MODULE_3__angular_router__["p" /* RouterModule */], [[2, __WEBPACK_IMPORTED_MODULE_3__angular_router__["u" /* ɵa */]], [2, __WEBPACK_IMPORTED_MODULE_3__angular_router__["l" /* Router */]]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](512, __WEBPACK_IMPORTED_MODULE_1__app_blog_blog_module__["a" /* BlogModule */], __WEBPACK_IMPORTED_MODULE_1__app_blog_blog_module__["a" /* BlogModule */], []),
        __WEBPACK_IMPORTED_MODULE_0__angular_core__["ɵmpd"](1024, __WEBPACK_IMPORTED_MODULE_3__angular_router__["j" /* ROUTES */], function () {
            return [[{ path: '', loadChildren: './welcome/welcome.module#WelcomeModule' },
                    { path: 'products', loadChildren: './products/products.module#ProductsModule' },
                    { path: 'order', loadChildren: './order/order.module#OrderModule' }, { path: 'resources',
                        loadChildren: './resources/resources.module#ResourcesModule' }, { path: 'news',
                        loadChildren: './news/news.module#NewsModule' }, { path: 'aboutus',
                        loadChildren: './aboutus/aboutus.module#AboutusModule' }, { path: 'dentca-3d',
                        loadChildren: './dentca-3d/dentca-3d.module#Dentca3dModule' }, { path: 'doctors',
                        loadChildren: './doctors/doctors.module#DoctorsModule' }]];
        }, [])]);
});
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ3JlYXQtc3Rhci9naXQvc2FsZXMtc3RvcmUvZnJvbnRlbmQvc3JjL2FwcC9ibG9nL2Jsb2cubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZ3JlYXQtc3Rhci9naXQvc2FsZXMtc3RvcmUvZnJvbnRlbmQvc3JjL2FwcC9ibG9nL2Jsb2cubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
//# sourceMappingURL=blog.module.ngfactory.js.map

/***/ }),

/***/ "../../../../../src/app/blog/blog.module.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return BlogModule; });
var BlogModule = (function () {
    function BlogModule() {
    }
    return BlogModule;
}());

//# sourceMappingURL=blog.module.js.map

/***/ })

});
//# sourceMappingURL=blog.module.chunk.js.map